"""remove unique constraint from trade_date

Revision ID: 14128badc72a
Revises: 010a086dd963
Create Date: 2026-04-13 22:17:44.623120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14128badc72a'
down_revision: Union[str, Sequence[str], None] = '010a086dd963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('trade_date'), table_name='stock_quotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('trade_date'), 'stock_quotes', ['trade_date'], unique=True)
    # ### end Alembic commands ###
