"""Add 'source' column to stock_quotes table.

Revision ID: 3958b871ea85
Revises: 14128badc72a
Create Date: 2026-05-01 19:04:59.792033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3958b871ea85'
down_revision: Union[str, Sequence[str], None] = '14128badc72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stock_quotes',
        sa.Column('source', sa.String(length=512), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_quotes', 'source')
    # ### end Alembic commands ###
